[package]
name = "mosquitto-mqtt-sys-rust"
version = "1.0.0"
authors = ["Aliev Yamanee <aliev.yamanee@teliacompany.com>"]
build = "build.rs"
edition = "2018"

[build-dependencies]
# bindgen = "0.51.1"

[dependencies]
